# -*- coding: utf-8 -*-
"""skripsi_fix_data_cleaning_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IJO_vDeYaLY0wztXfOEDwPslg35meH5

data cleaning

normalisasi struktur URL (penghapusan slash di akhir)
"""

import pandas as pd

df = pd.read_csv("/content/new_dataset_legitimate_3.csv")
df["url"] = df["url"].astype(str).str.rstrip("/")
df.to_csv("/content/new_dataset_legitimate_4.csv", index=False)

print("file tersimpan.")

"""cek isi data"""

import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

df = pd.read_csv("/content/new_dataset_legitimate_4.csv")

print(df.head())