# -*- coding: utf-8 -*-
"""skripsi_fix_data_merging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3CNQnqGFWKwR3PJoQt4TtLYRxl0zXhB
"""

import pandas as pd

df1 = pd.read_csv("/content/new_dataset_phishing_6.csv")
df2 = pd.read_csv("/content/new_dataset_legitimate_6.csv")

# gabungkan dataset
df_merge = pd.concat([df1, df2], ignore_index=True)

# simpan hasil gabungan
df_merge.to_csv("/content/new_all_dataset_merged.csv", index=False)

print("data berhasil digabung")
print("jumlah data:", len(df_merge))