# -*- coding: utf-8 -*-
"""skripsi_fix_data_shuffling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGA41m7Edkxa1kv-tveNgfcoFBTgzPCF

data shuffling
"""

import pandas as pd

df = pd.read_csv("/content/5050_15000_test_dataset.csv")
df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)

output_path = "/content/5050_15000_test_dataset_shuffled.csv"
df_shuffled.to_csv(output_path, index=False)

print("shuffling selesai", output_path)