# -*- coding: utf-8 -*-
"""skripsi_fix_data_balancing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9nS2CjGklHF4BwRQ8nKRQ9N-fmkZfjU
"""

import pandas as pd

df = pd.read_csv("/content/new_all_dataset_merged.csv")

# ambil 15000 phishing teratas
df_phishing = df[df["label"] == "phishing"].head(15000)

# ambil 15000 legitimate teratas
df_legitimate = df[df["label"] == "legitimate"].head(15000)

# gabungan
df_balanced = pd.concat([df_phishing, df_legitimate], ignore_index=True)

# done
df_balanced.to_csv("/content/new_all_dataset_balanced2.csv", index=False)
print("balancing selesai")