# -*- coding: utf-8 -*-
"""skripsi_fix_data_cleaning_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOwN_zMnLBaPM8afJiLS77IXUoNe71Rk

hapus duplikasi data dan menampilkan jumlah
"""

import pandas as pd

file_path = "/content/new_dataset_legitimate_6.csv"
df = pd.read_csv(file_path)

print("jumlah dataset sebelum hapus duplikasi:", len(df))

df_clean = df.drop_duplicates(subset=['url'])

print("jumlah dataset setelah hapus duplikasi:", len(df_clean))

"""menyimpan"""

output_path = "/content/new_dataset_legitimate_6.csv"
df_clean.to_csv(output_path, index=False)

print("done", output_path)

"""mengetahui jumlah yang terduplikat"""

import pandas as pd

file_path = "/content/new_dataset_legitimate_5.csv"
df = pd.read_csv(file_path)

# jumlah data awal
print("Jumlah total data:", len(df))

# pencarian url duplikat
duplicates = df[df.duplicated(subset=['url'], keep=False)]
duplicates = duplicates.sort_values(by='url')

# tampilkan url yang sama
print("\nDaftar URL yang sama:")
print(duplicates[['url']])

# jumlah baris yang duplikat
print("\nTotal baris yang memiliki URL sama:", len(duplicates))

# jumlah URL yang terduplikasi
print("Jumlah URL berbeda yang terduplikasi:", duplicates['url'].nunique())