# -*- coding: utf-8 -*-
"""skripsi_fix_attribute_reduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXk_KCbjOW5tZ5k6-9v0WYnb2xjvnp9k

attribute_reduction
"""

import pandas as pd

# dataset 1
df = pd.read_csv("/content/new_dataset_legitimate_1.csv")

df_url_only = df[["url"]]
df_url_only.to_csv("/content/new_dataset_legitimate_2.csv", index=False)

print("done.")

"""nampilin kolom"""

import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

df = pd.read_csv("/content/new_dataset_phishing_2.csv")

print(df.head())